add_payment_terms
Escodoo/egd-addons pull request #29
Opened 2023-12-01 15:09 UTC by augustodinizl

2023-12-01 15:21 UTC, marcelsavegnago commented
Acerta a mensagem do commit por favor

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message

https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html#commit-message-header

2023-12-01 15:29 UTC, marcelsavegnago requested changes

2023-12-01 15:29 UTC, marcelsavegnago commented on egd_purchase_custom/views/purchase_order_templates.xml
> +        id="egd_inherit_report_purchaseorder_document_add_payment_term"
Pode colocar o ID igua o o ID do inherit report_purchaseorder_document. Só daria problema se já tiver um id igual implementando no modulo.

2023-12-01 15:29 UTC, marcelsavegnago commented on egd_purchase_custom/views/purchase_quotation_templates.xml
> +        id="egd_inherit_report_purchasequotation_document_add_payment_term"
Pode colocar o ID igua o o ID do inherit report_purchaseorder_document. Só daria problema se já tiver um id igual implementando no modulo.

2023-12-01 15:33 UTC, augustodinizl commented on egd_purchase_custom/views/purchase_quotation_templates.xml
> +        id="egd_inherit_report_purchasequotation_document_add_payment_term"
> Pode colocar o ID igua o o ID do inherit report_purchaseorder_document. Só daria problema se já tiver um id igual implementando no modulo.

eu pensei em usar id diferente pra poder identificar no futuro o que ele faz só de bater o olho na lista de views

2023-12-01 15:52 UTC, kaynnan requested changes
@marcelsavegnago acho que poderiamos usar um unico arquivo conforme o addons do Purchase na Odoo: 

![image](https://github.com/Escodoo/egd-addons/assets/53870822/a765c657-4f82-45e5-be1c-73b2b63b6fc4)


Faltou um ponto importante tbm a importação do arquivo no `__manifest__.py`

2023-12-05 15:55 UTC, kaynnan requested changes
Referente ao históricos de commit, faz um git rebase -i HEAD~3 e junta com o comando `squash` no lugar de `pick` de baixo para cima até que fique somente um commit

Exemplo:

![image](https://github.com/Escodoo/egd-addons/assets/53870822/6ba60740-d101-4f3f-ba4c-696af6d433a6)

2023-12-05 16:14 UTC, kaynnan commented
@augustodinizl Outro erro que ocorre é na instalação do módulo por conta do id colocado nos templates:

`id="purchase_stock.report_purchasequotation_document_egd"`

Dessa maneira o Odoo tenta localizar dentro do módulo purchase_stock, o correto para declaração dos id seria:

`id="egd_inherit_report_purchasequotation_document"` e `id="egd_inherit_report_purchaseorder_document"`

Ajustando esses erros mencionados, o template funciona corretamente:

![image](https://github.com/Escodoo/egd-addons/assets/53870822/20682555-e762-402c-b05f-e6571e0bf4cb)
![image](https://github.com/Escodoo/egd-addons/assets/53870822/ef4a232a-9a1e-40db-854f-fe1b79bd4564)

2023-12-05 21:42 UTC, kaynnan approved these changes

2023-12-06 17:27 UTC, marcelsavegnago commented
Opa.. PR pronta ? Se sim coloca ela como pronta para revisão por favor

2023-12-11 19:10 UTC, augustodinizl commented
> Opa.. PR pronta ? Se sim coloca ela como pronta para revisão por favor

já fiz todas as alterações, o que tá blockando é o seu change request...

2023-12-11 20:34 UTC, marcelsavegnago approved these changes

2023-12-11 20:34 UTC, merged

2023-12-11 20:35 UTC, marcelsavegnago commented
@augustodinizl adiciona na task uma atividade para subir para o ambiente staging e prod por favor