[14.0][IMP] egd_hr_timesheet_custom: add employee_id field in account.analytic.line tree view
Escodoo/egd-addons pull request #36
Opened 2024-02-16 18:11 UTC by WesleyOliveira98

cc: @marcelsavegnago @kaynnan @douglascstd

![image](https://github.com/Escodoo/egd-addons/assets/69807420/4fbad80e-48b0-49c3-897e-2151d7dc177b)

2024-02-16 18:21 UTC, kaynnan requested changes
LGTM, somente realizar a alteração no Autor da view

2024-02-16 18:21 UTC, kaynnan commented on egd_hr_timesheet_custom/views/analytic_account_line.xml
> +     License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl). -->
Alterar para:

```

<!-- Copyright 2023 - TODAY, Wesley Oliveira <wesley.oliveira@escodoo.com.br>
     License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl). -->
     
```

2024-02-16 19:16 UTC, kaynnan approved these changes

2024-02-16 19:18 UTC, kaynnan requested changes

2024-02-16 19:18 UTC, kaynnan commented on egd_hr_timesheet_custom/__manifest__.py
> +    "depends": ["hr", "hr_timesheet", "account"],
O hr_timesheet já importa o hr, então não é necessário a declaração dele tbm

![image](https://github.com/Escodoo/egd-addons/assets/53870822/b583619b-fdd3-4853-88cc-c76be5746f76)

2024-02-16 19:23 UTC, kaynnan approved these changes
LGTM

2024-02-16 20:41 UTC, douglascstd approved these changes
Ok... revisão do código

2024-02-17 18:06 UTC, marcelsavegnago approved these changes

2024-02-17 18:07 UTC, merged