[ADD] egd_national_registration_expiry: add new module
Escodoo/egd-addons pull request #43
Opened 2024-03-20 16:13 UTC by Matthwhy

cc @marcelsavegnago @kaynnan @WesleyOliveira98

2024-03-20 19:52 UTC, WesleyOliveira98 requested changes
É necessário rodar o pre-commit antes de subir o commit, ele está apontando alguns pontos de formatação no código como aspas simples por exemplo

2024-03-21 14:13 UTC, WesleyOliveira98 approved these changes

2024-03-21 14:35 UTC, kaynnan approved these changes
LGTM

2024-03-22 14:52 UTC, marcelsavegnago approved these changes

2024-03-22 14:52 UTC, merged