[ADD] egd_import_vehicle_records: add new module
Escodoo/egd-addons pull request #45
Opened 2024-03-22 22:23 UTC by Matthwhy

cc @marcelsavegnago @kaynnan 

![image](https://github.com/Escodoo/egd-addons/assets/73322300/295c16f9-d5bd-4eca-b0a3-d86fb30a0231)

2024-03-24 18:06 UTC, marcelsavegnago commented
Não entendi o proposito deste módulo. O que foi solicitado pelo cliente ?

2024-03-25 12:47 UTC, Matthwhy commented
> Não entendi o proposito deste módulo. O que foi solicitado pelo cliente ?

@marcelsavegnago Então a proposta do módulo é que seja possível fazer as importações para registros do frota, por exemplo como acontece na egd, existe mudança de motorista no mesmo varias vezes durante o dia. E essa informação vem em planilha do rastreador, então com esse módulo e os novos campos que add seria possível importar essa planilha e ele gera todas as movimentações que teve, se teve troca de 5 motoristas, ele vai gerar um histórico de motorista para esses 5 . E assim é feito com o odômetro, o odômetro vai ser feito via importação também. E nesse modulo tem uma view, onde pode acompanhar as atualizações e ver qual ultima movimentação daquele veiculo

2024-03-25 18:20 UTC, marcelsavegnago commented
@kaynnan pode revisar e testar por favor ?

2024-03-25 20:44 UTC, kaynnan commented on egd_import_vehicle_records/models/fleet_vehicle.py
> +    hora_loc = fields.Char(string="Hora loc")
Variaveis e string devem seguir o padrão em Ingles

2024-03-25 20:53 UTC, kaynnan commented on egd_import_vehicle_records/views/fleet_vehicle.xml
> +                <field name="hora_loc" />
Não compreendi a utilização/inserção desses novos campos aindas, no sentido que eles vão ficar em brancos sem a possibilidade do usuário editar.

Eles teriam algum método para o auto preenchimento desses dados `address, hora_loc`?

2024-03-25 20:56 UTC, kaynnan requested changes

2024-03-25 20:56 UTC, kaynnan commented on egd_import_vehicle_records/models/fleet_vehicle.py
> +    hora_loc = fields.Char(string="Hora loc")
Outra questão seria o formato .Char, se ele é um campo para inserção ou auto preenchimento de horas, deveria ser do tipo Float, exemplo:

` time_start = fields.Float(string="Begin Hour")`

2024-03-25 21:02 UTC, kaynnan commented on egd_import_vehicle_records/views/fleet_vehicle.xml
> +        <field name="name">import records</field>
Manter o padrão da primeira letra em maiúsculo, 

![image](https://github.com/Escodoo/egd-addons/assets/53870822/2e5da0e9-3d79-4a2a-a098-a9bc1be29ffe)

2024-03-26 18:39 UTC, Matthwhy commented on egd_import_vehicle_records/views/fleet_vehicle.xml
> +                <field name="hora_loc" />
Então, a egd tem um controle de rastreamento dos seus veículos, que é feito por outro sistema, e é desse sistema que eles exportam as informações sobre os motoristas que dirigiram o veiculo, e esses dois campos que seria o ultimo local que o veiculo estava, e qual o horário. A ideia é que eles não permitam a alteração mesmo. Esses campos vão ser preenchidos com a planilha que vem do outro sistema

2024-03-26 18:52 UTC, Matthwhy commented on egd_import_vehicle_records/views/fleet_vehicle.xml
> +        <field name="name">import records</field>
![image](https://github.com/Escodoo/egd-addons/assets/73322300/f3d7fa30-4e76-4c4a-bb08-818777090119)

2024-03-26 21:08 UTC, kaynnan approved these changes
LGTM

2024-03-27 16:08 UTC, WesleyOliveira98 approved these changes

2024-04-01 15:40 UTC, merged