[14.0] [ADD] egd_stock_picking_custom2: add new module
Escodoo/egd-addons pull request #5
Opened 2023-09-20 01:41 UTC by rodrigonevest

2023-09-20 12:49 UTC, marcelsavegnago requested changes

2023-09-20 12:49 UTC, marcelsavegnago commented on egd_stock_picking_custom/models/stock_picking.py
> +    egd_responsible = fields.Many2one(
como é um campo many2one, muda o nome para egd_responsible_id

2023-09-20 15:58 UTC, kaynnan requested changes
![image](https://github.com/Escodoo/egd-addons/assets/53870822/726152bc-4090-40de-975e-0a00dcaedd91)

[REVIEW FUNCTIONAL] NOT APPROVED

Etapas para o erro:

HR > Personal Equipament > Personal Equipment Request > Picking > Action > Custody EGD

2023-09-20 15:58 UTC, kaynnan commented on egd_stock_picking_custom/report/egd_report_custody.xml
> +                                                            t-field="egd_product_certification.lot_ids.certificado"
Variavel errada, atualizar conforme o que foi refatorado no model

2023-09-20 18:08 UTC, kaynnan requested changes

2023-09-20 18:08 UTC, kaynnan commented on egd_stock_picking_custom/report/egd_report_custody.xml
> +                                                    t-field="o.egd_responsible.name"
![image](https://github.com/Escodoo/egd-addons/assets/53870822/f3e34608-9d23-4211-bb5b-c33e5265ddf6)

Quando faz o picking direto do Inventory -> Operations -> Transfer o nome do "Customer or Applicant" está vindo em branco

2023-09-21 19:52 UTC, rodrigonevest commented on egd_stock_picking_custom/report/egd_report_custody.xml
> +                                                    t-field="o.egd_responsible.name"
Essa foi uma solicitação do Douglas.

2023-09-21 21:46 UTC, kaynnan requested changes

2023-09-21 21:46 UTC, kaynnan commented on egd_stock_picking_custom/__manifest__.py
> +# Copyright 2023 Rodrigo Neves Trindade <rodrigo.trindade@escodoo.com.br>
Ajustar para -> # Copyright 2023 - TODAY, Escodoo

2023-09-21 22:17 UTC, kaynnan requested changes

2023-09-21 22:17 UTC, kaynnan commented on egd_stock_picking_custom/report/egd_report_custody.xml
Manter o padrão de reports QWeb dentro da pasta (views), segue abaixo o exemplo aplicado na poppi-addons:

![image](https://github.com/Escodoo/egd-addons/assets/53870822/e1200a7e-f092-49ed-a409-ff2301cdefaf)

2023-09-21 23:23 UTC, rodrigonevest commented on egd_stock_picking_custom/__manifest__.py
> +# Copyright 2023 Rodrigo Neves Trindade <rodrigo.trindade@escodoo.com.br>
feito

2023-09-21 23:23 UTC, rodrigonevest commented on egd_stock_picking_custom/report/egd_report_custody.xml
feito

2023-09-21 23:23 UTC, rodrigonevest commented on egd_stock_picking_custom/models/stock_picking.py
> +    egd_responsible = fields.Many2one(
feito

2023-10-03 21:29 UTC, kaynnan approved these changes
LGTM

Functional Review ✔

2023-10-03 21:53 UTC, marcelsavegnago requested changes

2023-10-03 21:53 UTC, marcelsavegnago commented on egd_stock_picking_custom/readme/DESCRIPTION.rst
> +EGD Cautela Report
Corrige este Cautela por favor e veja se tem mais alguma coisa em portugues.

2023-10-03 21:55 UTC, marcelsavegnago commented
@rodrigonevest outra coisa, roda o oca-gen-addon-readme --repo-name=$REPO --addon-dir=$MODULE --branch=$VERSION para o readme.rst ser gerado com base nos arquivos que estão na pasta README.

2023-10-09 14:38 UTC, marcelsavegnago commented
> @rodrigonevest outra coisa, roda o oca-gen-addon-readme --repo-name=$REPO --addon-dir=$MODULE --branch=$VERSION para o readme.rst ser gerado com base nos arquivos que estão na pasta README.

@rodrigonevest conseguiu avancar ?

2023-10-13 18:53 UTC, merged